version: '3.7'

services:
  db:
    image: postgres:14.2-alpine
    environment:
      - POSTGRES_USER=django
      - POSTGRES_PASSWORD=(9g_65x**tzds^oyw+zf_(t!p112cop0k(b8c#tgxj%ok06sp
      - POSTGRES_DB=demo
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
    expose:
      - "5432"
    volumes:
      - db_data:/var/lib/postgresql/data
  app:
    build:
      context: .
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./demo:/app
    command: sh -c "python manage.py runserver 0.0.0.0:8000"
    environment:
      - DEBUG=1
      - ALLOWED_HOSTS=localhost
      - EMAIL_HOST_USER=grodnopythonclassdemo@gmail.com
      - EMAIL_HOST_PASSWORD=faqcY5-taqses-gofcib
      - DB_NAME=demo
      - DB_USER=django
      - DB_PASSWORD=(9g_65x**tzds^oyw+zf_(t!p112cop0k(b8c#tgxj%ok06sp
      - DB_HOST=db
      - DB_PORT=5432
    depends_on:
      - db
volumes:
  db_data: